### ISSUE TITLE
license issue - bump utila to 0.4.0

### ISSUE THREAD

**Issue by tomas-mechura** [AriaMinaei/RenderKid#10]
Hello, 
we are trying to fix the licensing issues in our dependencies.
Could you please bump version of utila dependency to at least 0.4.0? The 0.4.0 version is adding LICENSE file to the package. 

Also can you please also bump the utila version in archived https://github.com/AriaMinaei/dom-converter, do the new release and use it here? I see that you are the maintainer, and as long the repo is archived I cannot add issues or PR there.

Thanks a lot.

**Comment by AriaMinaei** [comment]
Thanks for reporting these. They'll be in the next release :)

**Comment by opichals** [comment]
@AriaMinaei Could you please publish a patch release?

**Comment by AriaMinaei** [comment]
@opichals Published as 2.0.2 :)
