### ISSUE TITLE
css-select is outdated

### ISSUE THREAD

**Issue by stof** [AriaMinaei/RenderKid#18]
The package currently depends on version 2 of css-select. The latest version is version 4.
And the snyk vulnerability database reports a ReDoS vulnerability in css-what (dependency of css-select), that has been patched in the latest version, but still affects codebases using renderkid due to using an older version (see https://app.snyk.io/vuln/SNYK-JS-CSSWHAT-1298035). I don't know whether that vulnerability affects the usage done in renderkid, but tools checking dependencies against a vulnerability database still report it anyway.
It would be great if css-select could be updated to the latest version.

**Comment by alexd-shuttle** [comment]
New high-severity issue in css-what: https://github.com/advisories/GHSA-q8pj-2vqx-8ggc

Please update css-select to 4.1.3 which is compatible with the fixed css-what version 5.0.1.

**Comment by tschmidtb51** [comment]
#15 by @lopopolo should fix the issue.

**Comment by AriaMinaei** [comment]
Thanks @stof.

Renderkid 2.0.6 and pretty-error 3.0.4 should fix the audit, thanks to @AviVahl.

I should add that since we don't feed unsanitized input to css-select, it's rather unlikely the vulnerability would've affected any projects depending on renderkid or pretty-error.

**Comment by tschmidtb51** [comment]
Thank you!
