### ISSUE TITLE
Update NPM package.

### ISSUE THREAD

**Issue by aleclarson** [AriaMinaei/RenderKid#2]
[The NPM package](https://www.npmjs.com/package/renderkid) still installs the old `joiful-experiments` dependency. 

This causes problems when Node is above v0.10.x because `joiful-experiments` uses the deprecated `sys` module instead of the `util` module.

For now, I will change the dependency in `package.json` to `AriaMinaei/RenderKid` but it would be nice to keep the NPM package up-to-date so I can just use `renderkid`.

Thanks!

**Comment by AriaMinaei** [comment]
Thanks for the issue. I just pushed a new version for RenderKid and PrettyError. Although travis is failing in RenderKid but that's probably because of a problem in the testing packages.
