### ISSUE TITLE
Recent Version bump

### ISSUE THREAD

**Issue by CaseyPeters** [AriaMinaei/RenderKid#20]
Hi @AriaMinaei 

I noticed the recent version bump from v2.0.5 -> v2.0.6 included changes that seem pretty substantial. Specifically, I'm looking at https://github.com/AriaMinaei/RenderKid/commit/4a7e401a7c5f125405d85953bcd1d22c845ab28c &  https://github.com/AriaMinaei/RenderKid/commit/fa6ecbd4d32631ee619e2af3eac9a4fb2b9e2138

These changes include a lot of major version updates of a bunch of packages:

- mocha v5.2.0 -> v8.2.0
- css-select v2.0.2 -> v4.1.3
- htmlparser2 v3.10.1 -> v6.1.0
- strip-ansi v3.0.0 -> v6.0.0

I'm currently using [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin/tree/v2.28.0) which has the dependency `pretty-error ^2.0.2` which has the dependency `renderkid ^2.0.4`

due to the use of `^` in the version it is pulling in v2.0.6 which has completely broke this project.

Would it be possible to change the version to be a major version bump since all of the updates that you changed are also major version bumps? so the new version would be v3.0.0 instead of v2.0.6.

**Comment by AriaMinaei** [comment]
Hey @CaseyPeters, I just tried pretty-error 2.0.2 with renderkid 2.0.6 and the test passed. What exactly are the error you're encountering?

**Comment by souravbisht** [comment]
@AriaMinaei ,

In my package file:  **"html-webpack-plugin": "2.24.1",**
html-webpack-plugin has one of the dependencies  **"pretty-error": "^2.0.2"**, which has this dependency as **"renderkid": "^2.0.1"**

Error is as follows:

**PATH**/node_modules/html-webpack-plugin/node_modules/pretty-error/node_modules/renderkid/lib/RenderKid.js:10
**({cloneAndMergeDeep} = require('./tools'));**
 ^

**ReferenceError: Invalid left-hand side in assignment**
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by AriaMinaei** [comment]
It looks like a node compat problem, since it’s the destructuring statement that fails, likely because of our updating to coffeescript 2.x. Just to confirm, what’s your node version?

**Comment by souravbisht** [comment]
> It looks like a node compat problem, since it’s the destructuring statement that fails, likely because of our updating to coffeescript 2.x. Just to confirm, what’s your node version?

node version is 4.4.x.

**Comment by AriaMinaei** [comment]
Ok thanks. Yeah 4.4.x doesn't support destructuring syntax. I'm working on a fix now.

**Comment by AriaMinaei** [comment]
Okay, `renderkid 2.0.7` is out and it [works](https://github.com/AriaMinaei/pretty-error/runs/2795624567#step:5:6) with `node 4.x`. I fixed it by compiling down to ES3 and downgrading `strip-ansi` to `3.0.1`.

I should add that `node 4.x` has [been out of long-term support](https://nodejs.org/en/about/releases/) for a few years so we're not gonna support it for long either, but I'm not sure if breaking compatibility with an unmaintained node version constitutes a major semver release for `renderkid`. I'll read up on that for the next release (and please feel free to chime in).

**Comment by rosston** [comment]
My general sense is that dropping support for old node versions (even unmaintained ones) constitutes a breaking change in the npm community. From looking at [strip-ansi's commits](https://github.com/chalk/strip-ansi/commits/main), you can see that they bumped major versions twice (v4 and v5) apparently solely to drop support for older node versions.

I ended up here after looking at whether upgrading strip-ansi could happen in this project to resolve npm audit/dependabot warnings.
