### ISSUE TITLE
getCols for terminalWidth is broken

### ISSUE THREAD

**Issue by sompylasar** [AriaMinaei/RenderKid#5]
https://github.com/jonschlinkert/window-size/issues/4
https://nodejs.org/api/tty.html#tty_ws_columns
https://github.com/AriaMinaei/RenderKid/blob/master/src/tools.coffee#L75-L76

```
    cols =
          # ...
          else if process.stdout.columns and process.stdout.rows
            process.stdout.rows
```

**Comment by ChristianDavis** [comment]
https://github.com/AriaMinaei/RenderKid/pull/9

**Comment by AriaMinaei** [comment]
Thanks @ChristianDavis :+1:
