### ISSUE TITLE
Breaks Travis?

### ISSUE THREAD

**Issue by notatestuser** [AriaMinaei/RenderKid#7]
Apologies for the brief report - I don't have a lot of time to investigate this now. We seem to be getting this in our Travis build output. Has anyone else encountered this?

<img width="789" alt="screen shot 2017-03-03 at 13 11 08" src="https://cloud.githubusercontent.com/assets/1255926/23539002/fb13ff14-0012-11e7-8e19-0f77643cb9af.png">

**Comment by halt-hammerzeit** [comment]
Breaks Travis for me too.
Not Mac.

**Comment by notatestuser** [comment]
@AriaMinaei Do you think there's a solution we could apply here? We love using `html-webpack-plugin` but having our tests ignored due to this error is rather unexpected and inconvenient.

**Comment by AriaMinaei** [comment]
Hey @notatestuser I just pushed [this branch](https://github.com/AriaMinaei/RenderKid/tree/hotfix/possble-terminal-width-misread) which seems to be fixing the issue. Can you try it and confirm?

**Comment by notatestuser** [comment]
It works now and errors look nice again. Thanks @AriaMinaei!

**Comment by notatestuser** [comment]
Do you know when this will land in `master`?

**Comment by AriaMinaei** [comment]
@notatestuser Published :)
